#日志
logging.config: classpath:chao-logback.xml
log.path: /logs/chao/${spring.application.name}
log.maxHistory: 30

server:
  port: 3307
#spring
spring:
  application:
    name: chao-generator
  aop:  
    auto: true
  output:
    ansi:
      enabled: always 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://47.107.75.39:2032/jf_mybatis_back?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Kc&Q0m&xAhSP*3Qu0EPLHmVZaEzYtSae@@
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1
      test-on-borrow: true
      connection-init-sqls: SET NAMES utf8mb4;
      filter:
        wall:
          enabled: false
  thymeleaf:
    mode: LEGACYHTML5
    cache: false   
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl:  com.chao.cloud.common.extra.mybatis.log.Slf4jLogImpl

#默认使用本地数据源-代码自动生成
chao:
  cloud:
    codegen: #代码自动生成
        before:
          template-style: rest #rest 风格
        datasource:
          #url: ${spring.datasource.url}
          #username: ${spring.datasource.username}
          #password: ${spring.datasource.password}
          driver-name: ${spring.datasource.driver-class-name}
        package:
          parent: com.chao.cloud.generator #parent
        global:
         author: 南帅
        strategy:
         logic-delete-field-name: deleted
            